name: CI

on:
  - push
  - pull_request

# TODO this doesn't really do anything. Need to commit formatted changes, etc.

jobs:
  ci:
    name: CI (node ${{ matrix.command }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      matrix:
        node-version: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: yarn format
      - run: yarn lint
      - run: yarn test
      - run: yarn build

